### ISSUE TITLE
Using Ipfs instead of cdn

### ISSUE THREAD

**Issue by adelpro** [islamic-network/alquran.cloud#26]
Why not using [IPFS](https://ipfs.io/) network to distribute audio and media files instead of CDN.
benefits:
- the bandwidth will be distributed on the IPFS network.
- people can contribute by pinning files on their own ipfs nodes.

Im using this technique on my project [QuranIPFS](https://github.com/adelpro/Quranipfs) and its working perfectly.
Details:
Im hosting Ipfs node on digitalocean cloud as Backend, and using it to distribute 33 receiters audio files.
My website [www.quranipfs.com](https://www.quranipfs.com)

**Comment by meezaan** [comment]
@adelpro They are different things. A CDN is make distribute files over HTTP and speed and reliability are of vital importance, especially when doing things like streaming audio or video.

IPFS is a peer to peer file sharing protocol - it can't serve as a CDN. Even if it were to be used as a data source for an HTTP proxy that cached as a CDN, in a real peer to peer network there is no guarantee about the uptime or bandwidth of the peers, so it would defeat the purpose.

BTW I am unable to download audio from your website. Links like https://share.ipfs.io/#/QmPuR954yoKXWjoCr5ChsJZPjGZa819i7ePuy5QfbZ2nxz get stuck at loading file list.

**Comment by adelpro** [comment]
Thats the point @meezaan , peers not peer, when more peers join the project these files will become more reliable and beter then a CDN distributed from one server.
The project Quranipfs is a proof of concept and IPFS is on the early stage of development, 
How much cost distribuing files over CDN?!! And how mach data can we serve over CDN?!!

The inverse, how much cost distribuing files over IPFS and how much bandwidth and data can we serve?

IPFS is the future of file sharing especially with more and more modern browsers are adapting it by default eg Brave and Opera.

**Comment by meezaan** [comment]
> Thats the point @meezaan , peers not peer, when more peers join the project these files will become more reliable and beter then a CDN distributed from one server. The project Quranipfs is a proof of concept and IPFS is on the early stage of development, How much cost distribuing files over CDN?!! And how mach data can we serve over CDN?!!

What makes you think a CDN runs on one server? Almost all commercial CDNs allow specification of multiple origins, and the Islamic Network CDN is no different. The assumption that more peers will make things more reliable and better is simply incorrect. It depends, like I said before, on the reliability and connectivity of each peer. Peer to peer networks do no guarantee consistent performance. Besides, this idea of when is a fairy tale - any problem needs to be solved here and now, not at some point in the future. I don't have any problems using an IPFS network to share stuff, but using it as a CDN would be plain wrong.

> 
> The inverse, how much cost distribuing files over IPFS and how much bandwidth and data can we serve?

How would the cost be any different? Everyone has to pay for servers they provide to join the network and everyone has to pay for bandwidth. Then to actually be able to use IPFS as a CDN, someone still needs to pay for GeoDNS, failover, etc. etc. If anything, you could save money on bandwidth because you would not have to pay money to sync files all the time across your origins. This cost is something you would only be aware of at scale. The amount of data you distribute over a CDN or IPFS network is no different. You are restricted only by the CPU and memory required to serve HTTP requests and the network pipe. 

> 
> IPFS is the future of file sharing especially with more and more modern browsers are adapting it by default eg Brave and Opera.

File sharing and a CDN are 2 different things. I think you need to understand that first. It's like comparing a ream of linen (IPFS, which a protocol) to  jalabiya stitched of cotton (CDN, which is a finished product ready to use but uses a different protocol from IPFS - HTTP).

**Comment by meezaan** [comment]
I'll close this issue now as GitHub is not really the place for this discussion. Happy to continue it on Discord or https://community.islamic.network.
